services:
  strapi:
    build: .
    restart: always
    environment:
      NODE_ENV: production
      STRAPI_TELEMETRY_DISABLED: true
      PUBLIC_URL: https://api.amitrealestate.in
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_CLIENT: postgres
      DATABASE_HOST: strapi_postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: postgres://strapi:${POSTGRES_PASSWORD}@strapi_postgres:5432/strapi
    volumes:
      - strapi_data:/srv/app/storage
      - strapi_uploads:/srv/app/public/uploads
    expose:
      - 1337
    depends_on:
      strapi_postgres:
        condition: service_healthy
    # Ye command ensure karegi ki database ready hone ke baad hi Strapi start ho
    command: /bin/sh -c "until pg_isready -h strapi_postgres -p 5432 -U strapi; do echo waiting for database; sleep 2; done; npm run start"

  strapi_postgres:
    image: postgres:17-alpine
    container_name: strapi_postgres
    hostname: strapi_postgres
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - strapi_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U strapi -d strapi"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  strapi_data:
  strapi_uploads:
  strapi_postgres_data:
