services:
  strapi:
    build: .
    restart: always
    environment:
      NODE_ENV: production
      STRAPI_TELEMETRY_DISABLED: true
      PUBLIC_URL: https://api.amitrealestate.in
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_CLIENT: postgres
      DATABASE_HOST: amit-real-estate-db-jt2tsy
      DATABASE_PORT: 5432
      DATABASE_NAME: amit_db_strapi
      DATABASE_USERNAME: postgres
      # Password yahan direct likh diya hai
      DATABASE_PASSWORD: "Johny09"
      DATABASE_URL: "postgres://postgres:Johny09@amit-real-estate-db-jt2tsy:5432/amit_db_strapi"
    volumes:
      - strapi_data:/srv/app/storage
      - strapi_uploads:/srv/app/public/uploads
    expose:
      - 1337

volumes:
  strapi_data:
  strapi_uploads:
